### ISSUE TITLE
[REQUEST] MySql Support

### ISSUE THREAD

**Issue by yusufusta** [ricardoper/slim4-twig-skeleton#1]
Hi, your code is beautiful. There must be more stars.
I think you should add Mysql support, I didnt saw in your repos. Please add.

**Comment by ricardoper** [comment]
Hello @Quiec,

Thanks for your words and interest for this project.

You can add a Service Provider with a MySQL library at your choice. You can use PDO, MySQLi, Laravel Database, Doctrine, ...

The philosophy of this skeleton is to be as must slim and light as possible. The same philosophy of Slim Framework.

As MySQL is a widely used, in the coming days I will support this request. Wait a few days, please.

Once again, thanks for using this project.

**Comment by yusufusta** [comment]
I'm new to SlimPHP, I added Pdo myself but it is not compatible with the skeleton. I tried to apply it to the skeleton, but I don't know the MVC structure much.

I am waiting you. Thanks.

**Comment by ricardoper** [comment]
Hello @Quiec,

PDO is 100% compatible with this Skeleton. Like I mention, you need to create a Service Provider to load it in the DI.

I just release the v2.0.0 with Multi Database Support. Please, [read the README file to see details](https://github.com/ricardoper/slim4-twig-skeleton#database-support).

Enjoy it!!!

Thanks.

**Comment by yusufusta** [comment]
Its looking beautiful! Thanks you! Your code is best.
