### ISSUE TITLE
How to add Twig functions in a cleaning way

### ISSUE THREAD

**Issue by rickerd** [ricardoper/slim4-twig-skeleton#2]
I want to add Twig functions in a clean way.
Not changing the ViewMiddleware.php and adding the functions.

I have a TwigViewAbstract.php file that extends from the AbstractExtension. This is twig native but my functions are not loaded.
Can you provide help or an example?

**Comment by rickerd** [comment]
Never mind, I got it already!
Just load the abstract in the middleware.

```
        $customExtension = new TwigViewAbstract();
        $view->addExtension($customExtension);
```

**Comment by ricardoper** [comment]
Thanks @rickerd
