### ISSUE TITLE
Plaintext and json response examples

### ISSUE THREAD

**Issue by rickerd** [ricardoper/slim4-twig-skeleton#3]
Hi, me again.

Can you provide examples on how to use the plaintext response and the json response?
I want to return just a string or maybe a json response. Not always a twig file/template.

I've added the emitters but i don't see how to use it in a controller.

**Comment by ricardoper** [comment]
Hi @rickerd,

Have you checked the Demo Controllers?

You can see a little example that match your needs:
https://github.com/ricardoper/slim4-twig-skeleton/blob/master/app/Controllers/Demo/HomeController.php#L99

Have a look and tell me if you need more help.

Thanks,
Ricardo Pereira.

**Comment by rickerd** [comment]
Yes I see them. Thanks!!
